// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateConsultation(ctx context.Context, arg CreateConsultationParams) (Consultation, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConsultation(ctx context.Context, id uuid.UUID) error
	DeletePatient(ctx context.Context, id uuid.UUID) error
	GetConsultation(ctx context.Context, id uuid.UUID) (Consultation, error)
	GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListConsultationsByPatient(ctx context.Context, patientID uuid.UUID) ([]Consultation, error)
	ListDoctors(ctx context.Context) ([]User, error)
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error)
	UpdateConsultation(ctx context.Context, arg UpdateConsultationParams) error
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) error
}

var _ Querier = (*Queries)(nil)
